# Generated by Django 5.0.6 on 2024-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст записи'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время редактирования'),
        ),
    ]
