# Generated by Django 5.0.6 on 2024-08-31 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritephoto',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='favoritephoto',
            name='user',
        ),
        migrations.AddField(
            model_name='album',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_albums', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='photo',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_photos', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.DeleteModel(
            name='FavoriteAlbum',
        ),
        migrations.DeleteModel(
            name='FavoritePhoto',
        ),
    ]
