# Generated by Django 5.0.6 on 2024-08-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(max_length=300, verbose_name='Содержимое'),
        ),
    ]
