# Generated by Django 5.0.6 on 2024-08-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_favoritephoto_photo_remove_favoritephoto_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
